#! /usr/bin/env bash
INPUT_ARGS=${@//[]/-} # replace bizarre minuses with normal one
ARCH=$(uname -m)
source b

if [[ "$ARCH" == "x86_64" ]] ; then
    ../bin/trex-emu-proxy $INPUT_ARGS
else 
    echo "Default package supports only x86_64. Try compiling EMU for your platform."
    echo "https://github.com/cisco-system-traffic-generator/trex-emu "
fi
RESULT=$?

if [[ $RESULT != 0 ]]; then
    echo "TRex-EMU Proxy exited with a non zero code."
fi

exit $RESULT